---

verifier:
  name: inspec
  format: <%= ENV['CI'] ? 'junit' : 'cli' %>
  <% if ENV['CI'] %>
  output: "$CIRCLE_TEST_REPORTS/inspec/results/%{platform}_%{suite}_inspec.xml"
  <% end %>

platforms:
  - name: amazon-ec2
    driver:
      image_search:
        owner-id: 137112412989
        name: amzn-ami-hvm-2017.*x86_64-gp2
      tags:
        Name: kitchen-bonusbits-ecs-agent-amazon-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>

  - name: amazon-docker
    driver:
      image: amazonlinux:latest
      platform: rhel
      intermediate_instructions:
        - RUN yum -y install upstart procps util-linux
      pid_one_command: /sbin/init

  - name: rhel6
    driver:
      image_search:
        owner-id: 309956199498
        name: RHEL-6.*_HVM_GA-*-x86_64
      tags:
        Name: kitchen-bonusbits-ecs-agent-rhel6-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>

  - name: rhel7
    driver:
      image_search:
        owner-id: 309956199498
        name: RHEL-7.*_HVM_GA-*-x86_64
      tags:
        Name: kitchen-bonusbits-ecs-agent-rhel6-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>

suites:
  - name: ec2
    provisioner:
      name: chef_zero
      require_chef_omnibus: 12.18.31
      data_bags_path: test/data_bags
      encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
      roles_path: test/roles
      environments_path: test/environments
      client_rb:
        environment: kitchen
    driver:
      name: ec2
      associate_public_ip: <%= ENV['AWS_PUBLIC_IP'] %>
      aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
      security_group_ids:
      <% (1..5).collect { |n| ENV["AWS_SECURITY_GROUP_#{n}"] }.compact.each do |secgroup| %>
        - <%= secgroup %>
      <% end %>
      subnet_id: <%= ENV['AWS_SUBNET'] %>
      vpc_id: <%= ENV['AWS_VPC_ID'] %>
      iam_profile_name: <%= ENV['AWS_IAM_INSTANCE_PROFILE_1'] %>
      region: <%= ENV['AWS_REGION'] %>
      instance_type: t2.micro
    transport:
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
    run_list:
      - role[bonusbits_ecs_cluster]
    verifier:
      inspec_tests:
        - name: bootstrap
          git: https://github.com/bonusbits/inspec_bootstrap.git
        - name: bonusbits_base
          git: https://github.com/bonusbits/inspec_bonusbits_base.git
        - path: test/integration/inspec/profiles/bonusbits_ecs_cluster/
      attributes:
        chef_version: 12.18.31
        inside_aws: true
        configure_sudoers: true
    includes: [ 'amazon-ec2' ]

  - name: docker
    provisioner:
      name: chef_zero
      require_chef_omnibus: 12.18.31
      data_bags_path: test/data_bags
      encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
      roles_path: test/roles
      environments_path: test/environments
      client_rb:
        environment: kitchen
    driver:
      name: docker
      use_sudo: false # For Native Docker on Mac. Remove/Comment if using Toolbox (docker-machine)
      driver_config:
        ssl_verify_mode: ":verify_none"
    run_list:
      - role[bonusbits_ecs_cluster]
    verifier:
      inspec_tests:
        - name: bootstrap
          git: https://github.com/bonusbits/inspec_bootstrap.git
        - name: bonusbits_base
          git: https://github.com/bonusbits/inspec_bonusbits_base.git
        - path: test/integration/inspec/profiles/bonusbits_ecs_cluster/
      attributes:
        chef_version: 12.18.31
        inside_aws: false
        configure_sudoers: false
    includes: [ 'amazon-docker' ]