---
AWSTemplateFormatVersion: '2010-09-09'
Description: Autoscaling ECS Cluster
Parameters:
  # Ownership
  Owner:
    Type: String
    Default: FirstName LastName
  DeleteAfter:
    Type: String
    Default: 00/00/201x

  # Network
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>

  # Instance
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - m3.medium
    - m4.large
    - c3.medium
    - c4.medium
    Default: t2.medium
  OsType:
    Type: String
    AllowedValues:
    - amazon
#    - rhel6
#    - rhel7
#    - win12r2
#    - win16 # TODO: Add support for other OSs
    Default: amazon
  VolumeSize:
    Type: String
    Default: 100
  WarmEbs:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false

  # Autoscaling
  MinAutoScaleCount:
    Type: Number
    Default: 1
  MaxAutoScaleCount:
    Type: Number
    Default: 2
  AlarmSnsTopicArn:
    Type: String
    Default: arn:aws:sns:us-west-2:000000000000:alerts

  # Deployment
  CookbookName:
    Type: String
    Default: bonusbits_ecs_cluster
  CookbookVersion:
    Type: String
    Default: latest
  ChefDkVersion:
    Type: String
    Default: 1.3.40

Metadata:
  TemplateAuthor: Levon Becker
  AWS::CloudFormation::Interface:
    ParameterGroups:
      # Ownership
      - Label:
          default: Ownership
        Parameters:
          - Owner
          - DeleteAfter

      # Network
      - Label:
          default: Network
        Parameters:
          - VPC
          - Subnets
          - SecurityGroups

      # Instance
      - Label:
          default: Instance
        Parameters:
          - KeyPairName
          - InstanceType
          - OsType
          - VolumeSize
          - WarmEbs

      # Autoscaling
      - Label:
          default: Autoscaling
        Parameters:
          - MinAutoScaleCount
          - MaxAutoScaleCount
          - AlarmSnsTopicArn

      # Deployment
      - Label:
          default: Deployment
        Parameters:
          - CookbookName
          - CookbookVersion
          - ChefDkVersion

    ParameterLabels:
      # Ownership
      Owner:
        default: Team or Individual Owner
      DeleteAfter:
        default: Delete After Date

      # Network
      VPC:
        default: VPC ID
      Subnets:
        default: Subnet List
      SecurityGroups:
        default: Security Group List

      # Instance
      KeyPairName:
        default: EC2 Key Pair Name
      InstanceType:
        default: Instance Type
      OsType:
        default: Agent OS
      VolumeSize:
        default: Volume Size
      WarmEbs:
        default: Warm EBS

      # Autoscaling
      MinAutoScaleCount:
        default: Min AutoScale Count
      MaxAutoScaleCount:
        default: Max AutoScale Count
      AlarmSnsTopicArn:
        default: Alarm SNS Topic ARN

      # Deployment
      CookbookName:
        default: Cookbook Name
      CookbookVersion:
        default: Cookbook Version
      ChefDkVersion:
        default: ChefDK Version

Outputs:
  # Ownership
  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner
  DeleteAfter:
    Description: It is ok to delete the Formation after this date.
    Value: !Ref DeleteAfter

  # Network
  VPC:
    Value: !Ref VPC
  Subnets:
    Value: !Join [',', !Ref Subnets]
  SecurityGroups:
    Value: !Join [',', !Ref SecurityGroups]

  # Instance
  KeyPairName:
    Description: Key Pair Name Used.
    Value: !Ref KeyPairName
  InstanceType:
    Description: Instance Type Used.
    Value: !Ref InstanceType
  OsType:
    Description: OS Type Used.
    Value: !Ref OsType
  VolumeSize:
    Description: Cluster Instance Volume Size.
    Value: !Ref VolumeSize
  WarmEbs:
    Description: Warm EBS Volume.
    Value: !Ref WarmEbs

  # Autoscaling
  MinAutoScaleCount:
    Value: !Ref MinAutoScaleCount
  MaxAutoScaleCount:
    Value: !Ref MaxAutoScaleCount
  AlarmSnsTopicArn:
    Value: !Ref AlarmSnsTopicArn

  # Deployment
  CookbookName:
    Value: !Ref CookbookName
  CookbookVersion:
    Value: !Ref CookbookVersion
  ChefDkVersion:
    Value: !Ref ChefDkVersion

  # Generated
  AMI:
    Description: AMI Used.
    Value: !FindInMap [ RegionMap, !Ref "AWS::Region", !Ref "OsType" ]
  IAMRole:
    Description: IAM Instance Profile Role Created.
    Value: !Ref IamRole

Mappings:
  RegionMap:
    # Amazon Linux AMI 2017.03 was released on 2017-04-04
    # Red Hat Enterprise Linux AMI 6.9 was released on 2017-03-19
    # Red Hat Enterprise Linux AMI 7.3 was released on 2016-09-06
      # N. Virginia
      us-east-1:
        amazon: ami-22ce4934
      # Ohio
      us-east-2:
        amazon: ami-7bfcd81e
      # Oregon
      us-west-2:
        amazon: ami-8ca83fec
        rhel6: ami-d61a92b6
        rhel7: ami-38fd2558
        win12r2: ami-09f47d69
        win16: ami-94e26af4
      # N. California
      us-west-1:
        amazon: ami-9e247efe
      # Canada
      ca-central-1:
        amazon: ami-8601bce2
      # Ireland
      eu-west-1:
        amazon: ami-e5083683
      # London
      eu-west-2:
        amazon: ami-11130775
      # Frankfurt
      eu-central-1:
        amazon: ami-5b06d634
      # Singapore
      ap-southeast-1:
        amazon: ami-a2bc03c1
      # Seoul
      ap-northeast-1:
        amazon: ami-8369baed
      # Tokyo
      ap-northeast-2:
        amazon: ami-859bbfe2
      # Sydney
      ap-southeast-2:
        amazon: ami-8bf2fde8
      # Mumbai
      ap-south-1:
        amazon: ami-815625ee
      # Sao Paulo
      sa-east-1:
        amazon: ami-a97013c5
      # Beijing
      cn-north-1:
        amazon: ami-b3d80ede
      # GovCloud
      us-gov-west-1:
        amazon: ami-700a8f11

Conditions:
  HasKeyPair: !Not [!Equals [ !Ref KeyPairName, '' ]]
  WarmEbsVolume: !Equals [ !Ref WarmEbs, 'true' ]
  AmazonHost: !Equals [ !Ref OsType, 'amazon' ]
  RhelHost: !Or [
    !Equals [ !Ref OsType, 'rhel6' ],
    !Equals [ !Ref OsType, 'rhel7' ]
  ]
  LinuxHost: !Or [
    !Equals [ !Ref OsType, 'amazon' ],
    !Equals [ !Ref OsType, 'centos' ],
    !Equals [ !Ref OsType, 'suse' ],
    !Equals [ !Ref OsType, 'rhel6' ],
    !Equals [ !Ref OsType, 'rhel7' ],
    !Equals [ !Ref OsType, 'ubuntu' ]
  ]
  RhelFamily: !Or [
    !Equals [ !Ref OsType, 'amazon' ],
    !Equals [ !Ref OsType, 'centos' ],
    !Equals [ !Ref OsType, 'rhel6' ],
    !Equals [ !Ref OsType, 'rhel7' ]
  ]
  WindowsHost: !Or [
    !Equals [ !Ref OsType, 'win12r2' ],
    !Equals [ !Ref OsType, 'win16' ]
  ]

Resources:
  # CloudWatch
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref "AWS::StackName"
      RetentionInDays: '30'

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref "AWS::StackName"

  # IAM
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AWS::StackName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  IamPolicies:
    Type: AWS::IAM::Policy
    DependsOn: IamRole
    Properties:
      PolicyName: !Join [ '', [ !Ref "AWS::StackName", -instance-policy ] ]
      Roles: [!Ref IamRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        # Allow Full S3 Access
        - Effect: Allow
          Action:
          - s3:*
          Resource: "*"
        # Allow Read/Write Route53 for Userdata Script DNS A Record Set
        - Effect: Allow
          Action:
          - route53:ChangeResourceRecordSets
          - route53:Get*
          - route53:List*
          Resource: "*"
        # Allow Write CloudWatch Logs
        - Effect: Allow
          Action:
          - cloudwatch:PutMetricData
          Resource: "*"
        - Effect: Allow
          Action:
          - logs:PutLogEvents
          - logs:CreateLogStream
          - logs:DescribeLogStreams
          - logs:CreateLogGroup
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:logs:'
              - !Ref AWS::Region
              - ":"
              - !Ref AWS::AccountId
              - ":log-group:"
              - !Ref CloudWatchLogsGroup
              - ":log-stream:*"
        # Extra ECS Access
        - Effect: Allow
          Action:
          - ecs:RegisterTaskDefinition
          - ecs:ListClusters
          - ecs:DescribeContainerInstances
          - ecs:Poll
          - ecs:RunTask
          - ecs:StopTask
          - ecs:ListContainerInstances
          Resource: "*"

  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: IamRole
    Properties:
      Path: "/"
      Roles: [!Ref IamRole]

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn:
      - LaunchConfiguration
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: !Ref MinAutoScaleCount
      MaxSize: !Ref MaxAutoScaleCount
      DesiredCapacity: !Ref MinAutoScaleCount
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupMinSize
            - GroupMaxSize
            - GroupDesiredCapacity
            - GroupInServiceInstances
            - GroupPendingInstances
            - GroupStandbyInstances
            - GroupTerminatingInstances
            - GroupTotalInstances
      NotificationConfigurations:
        - TopicARN: !Ref AlarmSnsTopicArn
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          Value: !Ref "AWS::StackName"
          PropagateAtLaunch: true
        - Key: Owner
          Value: !Ref Owner
          PropagateAtLaunch: true
        - Key: DeleteAfter
          Value: !Ref DeleteAfter
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: !Ref MinAutoScaleCount
        Timeout: PT30M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !Ref MinAutoScaleCount
        MaxBatchSize: 1

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn:
      - IamInstanceProfile
      - EcsCluster
    Properties:
      AssociatePublicIpAddress: false
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", !Ref "OsType" ]
      SecurityGroups: !Ref SecurityGroups
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref IamInstanceProfile
      KeyName: !If [ HasKeyPair, !Ref KeyPairName, !Ref "AWS::NoValue"]
      InstanceMonitoring: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: gp2
            VolumeSize: !Ref VolumeSize
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install -y aws-cfn-bootstrap aws-cli cloud-init git
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region} --configsets ec2_setup
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          ec2_setup:
            - config_cfn
            - install_chefdk
            - setup_chef_client
            - run_chef_client
            - warm_ebs
        config_cfn:
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: '000400'
              owner: root
              group: root
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LaunchConfiguration.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region} --configsets ec2_setup
                runas=root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
        install_chefdk:
          commands:
            01_install_chefdk:
              command: !Sub "curl -L https://omnitruck.chef.io/install.sh | bash -s -- -P chefdk -v ${ChefDkVersion}"
        setup_chef_client:
          commands:
            01_mkdir_chef_repo:
              command: "mkdir -p /opt/chef-repo"
            02_mkdir_chef_repo_subdirs:
              cwd: /opt/chef-repo
              command: "mkdir -p cookbooks checksums environments cache backup data_bags roles"
            03_download_cookbook:
              cwd: /opt/chef-repo/cookbooks
              command: !Sub "git clone --branch ${CookbookVersion} https://github.com/bonusbits/${CookbookName}.git"
            04_download_dependent_cookbooks:
              cwd: !Sub "/opt/chef-repo/cookbooks/${CookbookName}"
              command: !Sub "export HOME=/root && /opt/chefdk/embedded/bin/berks vendor /opt/chef-repo/cookbooks/"
          files:
            "/opt/chef-repo/client.rb":
              content: !Sub |
                node_name 'ec2_node'
                checksum_path '/opt/chef-repo/checksums'
                file_cache_path '/opt/chef-repo/cache'
                file_backup_path '/opt/chef-repo/backup'
                cookbook_path '/opt/chef-repo/cookbooks'
                data_bag_path '/opt/chef-repo/data_bags'
                environment_path '/opt/chef-repo/environments'
                role_path '/opt/chef-repo/roles'
                chef_server_url 'http://127.0.0.1:8889'
                encrypted_data_bag_secret '/opt/chef-repo/encrypted_data_bag_secret'
                log_level :info
                log_location '/var/log/chef-client.log'
                verify_api_cert false
            "/opt/chef-repo/environments/aws.json":
              content: !Sub |
               {
                   "name": "aws",
                   "description": "Environment",
                   "cookbook_versions": {},
                   "json_class": "Chef::Environment",
                   "chef_type": "environment",
                   "default_attributes": {
                   },
                   "override_attributes": {
                       "bonusbits_base": {
                           "cloudwatch_logs": {
                               "logs_group_name": "${CloudWatchLogsGroup}"
                           }
                       },
                       "bonusbits_ecs_cluster": {
                           "cluster_name": "${EcsCluster}"
                       }
                   }
               }
        run_chef_client:
          commands:
            01_run_chef:
              command: !Sub "/opt/chefdk/bin/chef-client -z -o 'recipe[${CookbookName}]' --environment 'aws' --config /opt/chef-repo/client.rb --log_level info --force-formatter --chef-zero-port 8889"
        warm_ebs:
          Condition: WarmEbsVolume
          commands:
            01_warm_ebs:
              command: "#echo 'ACTION: Performing EBS Warming' && dd if=/dev/xvda of=/dev/xvda conv=notrunc bs=1M status=progress"

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn:
      - AutoScalingGroup
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref AutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: 1

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn:
      - AutoScalingGroup
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref AutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: -1

  MemoryAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleUpPolicy
      - EcsCluster
    Properties:
      AlarmName: !Join [ '', [ !Ref "AWS::StackName", '-mem-high' ]]
      AlarmDescription: Scale-up if Memory > 80% for 10 minutes
      MetricName: MemoryReservation
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      AlarmActions:
        - !Ref ScaleUpPolicy
      OKActions:
        - !Ref AlarmSnsTopicArn
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsCluster
      ComparisonOperator: GreaterThanThreshold

  MemoryAlarmLow:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleDownPolicy
      - EcsCluster
    Properties:
      AlarmName: !Join [ '', [ !Ref "AWS::StackName", '-mem-low' ]]
      AlarmDescription: Scale-down if Memory < 30% for 15 minutes
      MetricName: MemoryReservation
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 30
      AlarmActions:
        - !Ref ScaleDownPolicy
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsCluster
      ComparisonOperator: LessThanThreshold

  CPUAlarmHigh: # TODO: Doesn't Seem to be working
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleUpPolicy
      - EcsCluster
    Properties:
      AlarmName: !Join [ '', [ !Ref "AWS::StackName", '-cpu-high' ]]
      AlarmDescription: Alert if CPU > 80% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      AlarmActions:
        - !Ref ScaleUpPolicy
      OKActions:
        - !Ref AlarmSnsTopicArn
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsCluster
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow: # TODO: Doesn't Seem to be working
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleDownPolicy
      - EcsCluster
    Properties:
      AlarmName: !Join [ '', [ !Ref "AWS::StackName", '-cpu-low' ]]
      AlarmDescription: Alert if CPU < 30% for 15 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 30
      AlarmActions:
        - !Ref ScaleDownPolicy
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsCluster
      ComparisonOperator: LessThanThreshold